package DCMS_FrontEnd;


/**
* DCMS_FrontEnd/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, August 4, 2017 10:55:50 PM EDT
*/

public interface FrontEndOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phoneNumber, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String courseRegistered, String status, String statusDate);
  String recordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface FrontEndOperations
